authors/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from authors.views.api import AuthorAPIV2ViewSet

from . import views

app_name = 'authors'

authors_api_v2_router = SimpleRouter()
authors_api_v2_router.register(
    'api/v2',
    AuthorAPIV2ViewSet,
    basename='authors-api-v2'
)

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path(
        'dashboard/recipe/create/',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_create'
    ),
    path(
        'dashboard/recipe/delete/',
        views.DashboardRecipeDelete.as_view(),
        name='dashboard_recipe_delete'
    ),
    path(
        'dashboard/recipe/<int:id>/edit/',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_edit'
    ),
    path(
        'profile/<int:id>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path('', include(authors_api_v2_router.urls))
]

recipes/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from recipes import views

app_name = 'recipes'

recipe_api_v2_router = SimpleRouter()
recipe_api_v2_router.register(
    'recipes/api/v2',
    views.RecipeAPIV2ViewSet,
    basename='recipes-api-v2'
)

urlpatterns = [
    path(
        '',
        views.RecipeListViewHome.as_view(),
        name='home'
    ),
    path(
        'recipes/search/',
        views.RecipeListViewSearch.as_view(),
        name='search'
    ),
    path(
        'recipes/category/<int:category_id>/',
        views.RecipeListViewCategory.as_view(),
        name='category'
    ),
    path(
        'recipes/tags/<slug:slug>/',
        views.RecipeListViewTag.as_view(),
        name='tag'
    ),
    path(
        'recipes/<int:pk>/',
        views.RecipeDetailView.as_view(),
        name='recipe'
    ),
    path(
        'recipes/api/v1/',
        views.RecipeListViewHomeApi.as_view(),
        name='recipes_api_v1'
    ),
    path(
        'recipes/api/v1/<int:pk>',
        views.RecipeDetailViewApi.as_view(),
        name='recipes_api_v1_detail'
    ),
    path(
        'recipes/theory/',
        views.theory,
        name='theory'
    ),
    path(
        'recipes/api/v2/tag/<int:pk>/',
        views.tag_api_detail,
        name='recipes_api_v2_tag'
    ),
    path(
        'recipes/api/v2/token/',
        TokenObtainPairView.as_view(),
        name='token_obtain_pair'
    ),
    path(
        'recipes/api/v2/token/refresh/',
        TokenRefreshView.as_view(),
        name='token_refresh'
    ),
    path('recipes/api/v2/token/verify/',
         TokenVerifyView.as_view(), name='token_verify'),
    path('', include(recipe_api_v2_router.urls)),
]

recipes/views.py
import os

from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.db.models.aggregates import Count
from django.db.models.fields.files import ImageFieldFile
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.http.response import Http404
from django.shortcuts import render
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView

from tag.models import Tag
from utils.pagination import make_pagination

from .models import Recipe

PER_PAGE = int(os.environ.get('PER_PAGE', 3))

# Create your views here.


def theory(request):
    recipes = Recipe.objects.get_published()
    number_of_recipes = recipes.aggregate(number=Count('id'))

    return render(
        request,
        'recipes/pages/theory.html',
        context={
            'recipes': recipes,
            'number_of_recipes': number_of_recipes['number'],
        }
    )


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(is_published=True)

        query_set = query_set.select_related(
            'author', 'category', 'author__profile')
        query_set = query_set.prefetch_related('tags')

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        page_obj, pagination_range = make_pagination(
            self.request,
            context.get('recipes'),
            PER_PAGE
        )

        html_language = translation.get_language()

        context.update({
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'html_language': html_language,
        })

        return context


class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'


class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data().get('recipes').object_list.values()

        return JsonResponse(list(recipes), safe=False)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            category_id=self.kwargs.get('category_id')
        )

        if not query_set:
            raise Http404()

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')

        context.update({
            'title': (
                f'{context.get("recipes")[0].category.name} - '
                f'{category_translation} | '
            ),
        })

        return context


class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(tags__slug=self.kwargs.get('slug', ''))

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        title = Tag.objects.filter(slug=self.kwargs.get('slug', '')).first()

        if not title:
            title = 'No recipes found'

        title = f'{title} - Tag'

        context.update({
            'title': f'{title} | ',

        })

        return context


class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        if not search_term:
            raise Http404()

        query_set = query_set.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term)
            )
        )

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        context.update({
            'title': f'Search for "{search_term}" | ',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })

        return context


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(is_published=True)

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'is_detail_page': True,
        })

        return context


class RecipeDetailViewApi(RecipeDetailView):
    class RecipeEncoder(DjangoJSONEncoder):
        def __init__(self, request, **kwargs) -> None:
            super().__init__(**kwargs)
            self.request = request

        def default(self, o):
            if isinstance(o, ImageFieldFile):
                return self.request.get_host() + o.url

            return super().default(o)

    def render_to_response(self, context, **response_kwargs):
        recipe_model = self.get_context_data().get('recipe')
        recipe_dict = model_to_dict(
            recipe_model,
            exclude=['is_published', 'preparation_steps_is_html']
        )

        recipe_dict.update({
            'created_at': recipe_model.created_at,
            'updated_at': recipe_model.updated_at,
        })

        return JsonResponse(
            recipe_dict,
            encoder=self.RecipeEncoder,
            safe=False,
            json_dumps_params={
                'indent': 2,
                'request': self.request,
            }
        )

recipes/views/api.py
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from recipes.models import Recipe
from recipes.permissions import IsOwner
from recipes.serializer import RecipeSerializer
from tag.models import Tag
from tag.serializer import TagSerializer
from utils.strings import is_positive_number


class RecipeAPUV2Pagination(PageNumberPagination):
    page_size = 1


class RecipeAPIV2ViewSet(ModelViewSet):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = RecipeAPUV2Pagination
    permission_classes = [IsAuthenticatedOrReadOnly, ]
    http_method_names = ['get', 'options', 'head', 'post', 'patch', 'delete']

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    def get_object(self):
        pk = self.kwargs.get('pk', '')
        obj = get_object_or_404(
            self.get_queryset(),
            pk=pk,
        )

        self.check_object_permissions(self.request, obj)

        return obj

    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsOwner(), ]
        return super().get_permissions()

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)

        category_id = self.request.query_params.get('category_id')

        if category_id is not None and is_positive_number(category_id):
            qs = qs.filter(category_id=category_id)

        return qs


@api_view()
def tag_api_detail(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    serializer = TagSerializer(instance=tag)

    return Response(serializer.data)

recipes/views/site.py
import os

from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.db.models.aggregates import Count
from django.db.models.fields.files import ImageFieldFile
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.http.response import Http404
from django.shortcuts import render
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView

from tag.models import Tag
from utils.pagination import make_pagination

from ..models import Recipe

PER_PAGE = int(os.environ.get('PER_PAGE', 3))

# Create your views here.


def theory(request):
    recipes = Recipe.objects.get_published()
    number_of_recipes = recipes.aggregate(number=Count('id'))

    return render(
        request,
        'recipes/pages/theory.html',
        context={
            'recipes': recipes,
            'number_of_recipes': number_of_recipes['number'],
        }
    )


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(is_published=True)

        query_set = query_set.select_related(
            'author', 'category', 'author__profile')
        query_set = query_set.prefetch_related('tags')

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        page_obj, pagination_range = make_pagination(
            self.request,
            context.get('recipes'),
            PER_PAGE
        )

        html_language = translation.get_language()

        context.update({
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'html_language': html_language,
        })

        return context


class RecipeListViewHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'


class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data().get('recipes').object_list.values()

        return JsonResponse(list(recipes), safe=False)


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            category_id=self.kwargs.get('category_id')
        )

        if not query_set:
            raise Http404()

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        category_translation = _('Category')

        context.update({
            'title': (
                f'{context.get("recipes")[0].category.name} - '
                f'{category_translation} | '
            ),
        })

        return context


class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(tags__slug=self.kwargs.get('slug', ''))

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        title = Tag.objects.filter(slug=self.kwargs.get('slug', '')).first()

        if not title:
            title = 'No recipes found'

        title = f'{title} - Tag'

        context.update({
            'title': f'{title} | ',

        })

        return context


class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        if not search_term:
            raise Http404()

        query_set = query_set.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term)
            )
        )

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()

        context.update({
            'title': f'Search for "{search_term}" | ',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
        })

        return context


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(is_published=True)

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'is_detail_page': True,
        })

        return context


class RecipeDetailViewApi(RecipeDetailView):
    class RecipeEncoder(DjangoJSONEncoder):
        def __init__(self, request, **kwargs) -> None:
            super().__init__(**kwargs)
            self.request = request

        def default(self, o):
            if isinstance(o, ImageFieldFile):
                return self.request.get_host() + o.url

            return super().default(o)

    def render_to_response(self, context, **response_kwargs):
        recipe_model = self.get_context_data().get('recipe')
        recipe_dict = model_to_dict(
            recipe_model,
            exclude=['is_published', 'preparation_steps_is_html']
        )

        recipe_dict.update({
            'created_at': recipe_model.created_at,
            'updated_at': recipe_model.updated_at,
        })

        return JsonResponse(
            recipe_dict,
            encoder=self.RecipeEncoder,
            safe=False,
            json_dumps_params={
                'indent': 2,
                'request': self.request,
            }
        )

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
/>
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/brands.min.css"
    integrity="sha512-W/zrbCncQnky/EzL+/AYwTtosvrM+YG/V6piQLSe2HuKS6cmbw89kjYkp3tWFn1dkWV7L1ruvJyKbLz73Vlgfg=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
/>
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/solid.min.css"
    integrity="sha512-P9pgMgcSNlLb4Z2WAB2sH5KBKGnBfyJnq+bhcfLCFusrRc4XdXrhfDluBl/usq75NF5gTDIMcwI1GaG5gju+Mw=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href={% static "recipes/css/style.css" %}>

recipes/templates/recipes/partials/recipe.html
{% load i18n %}

<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{{ recipe.get_absolute_url }}">
                <img src="{{ recipe.cover.url }}" alt="temp">
            </a>
        </div>
    {% endif %}

    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{{ recipe.get_absolute_url }}">
                {{ recipe.title }}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                {% if recipe.author.profile %}
                <a href="{% url "authors:profile" recipe.author.profile.id %}">
                {% endif %}
                    
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                {{ recipe.author.username }}
                {% endif %}

                {% if recipe.author.profile %}
                </a>
                {% endif %}
            </span>
        {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"M j, Y, P" }}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url "recipes:category" recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> {% translate "Preparation" %}</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> {% translate "Servings" %}</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if not is_detail_page %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" 
                href="{{ recipe.get_absolute_url }}">
                <i class="fas fa-eye"></i>
                <span>{% translate "read more" %}...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
            
            {% if recipe.tags.all %}
            <p class="recipe-tags">
                Tags:
                {% for tag in recipe.tags.all %}
                <a href="{% url "recipes:tag" tag.slug %}">{{ tag.name }}</a>,
                {% endfor %}
            </p>
            {% endif %}
        </div>
    {% endif %}
</div>